### ISSUE TITLE
Combine scripts?

### ISSUE THREAD

**Issue by bordenc** [littledot/bank-of-canada-exchange-rates#1]
Since GitHub doesn't allow DMs, I'm broaching this as an 'issue' request. I whipped up a similar script at https://github.com/bordenc/py_scripts/blob/main/bocfx.py . I'm grateful for feedback, and I am offering to let you graft my script into yours.

If I understand your script correctly, the purpose is to download annual FX rates for all known currencies and save them in a CSV.

In contrast, my script looks up FX rates for a date or a range of dates, but for only one currency. In theory, the output can pipe to a file or the dict can be exported to a file. I could probably extend the script to support multiple currencies in a single request, as yours seems to.

Anyhow, feel free to close as won't fix if you're not interested. Otherwise, I'd be happy to collaborate on your script if there are other people out there who can use it.

**Comment by littledot** [comment]
No thanks.
